let channels=[], current=null, hls=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function init(){channels=await fetch('assets/channels.json').then(r=>r.json()); renderFilters(); renderRows(channels); bind();}
function renderFilters(){const cats=['All',...new Set(channels.map(c=>c.category))]; $('#filters').innerHTML=cats.map((c,i)=>`<button class="filter ${i?'':'active'}" data-cat="${esc(c)}">${esc(c)}</button>`).join(''); $$('.filter').forEach(b=>b.onclick=()=>{ $$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active'); renderRows(b.dataset.cat==='All'?channels:channels.filter(c=>c.category===b.dataset.cat)); });}
function renderRows(list){let groups=[...new Set(list.map(c=>c.category))];$('#rows').innerHTML=groups.map(cat=>{let items=list.filter(c=>c.category===cat);return `<section class="row"><div class="row-head"><h3>${esc(cat)}</h3><span class="row-count">${items.length} channel${items.length>1?'s':''}</span></div><div class="cards">${items.map(card).join('')}</div></section>`}).join(''); $$('.card').forEach(c=>c.onclick=()=>openPlayer(c.dataset.id));}
function card(c){return `<article class="card" data-id="${esc(c.id)}"><span class="live-badge"><i></i>LIVE</span><img src="${esc(c.logo)}" alt="" loading="lazy" onerror="this.style.display='none'"><div class="card-info"><div class="card-name">${esc(c.name)}</div><div class="card-cat">${esc(c.category)}</div></div></article>`}
function openPlayer(id){current=channels.find(c=>String(c.id)===String(id)); if(!current)return; $('#playerTitle').textContent=current.name;$('#playerCategory').textContent=current.category.toUpperCase();$('#playerModal').classList.add('open');$('#videoError').style.display='none';$('#videoLoading').style.display='flex';loadStream();}
function loadStream(){const v=$('#video'); if(hls){hls.destroy();hls=null}v.removeAttribute('src');v.load(); const url=current.url; if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true});hls.loadSource(url);hls.attachMedia(v);hls.on(Hls.Events.MANIFEST_PARSED,()=>{hideLoading();v.play().catch(()=>{});});hls.on(Hls.Events.ERROR,(e,d)=>{if(d.fatal)showError();});}else if(v.canPlayType('application/vnd.apple.mpegurl')){v.src=url;v.addEventListener('loadedmetadata',()=>{hideLoading();v.play().catch(()=>{});},{once:true});v.addEventListener('error',showError,{once:true});}else showError();}
function hideLoading(){$('#videoLoading').style.display='none';$('#videoError').style.display='none'} function showError(){$('#videoLoading').style.display='none';$('#videoError').style.display='flex'}
function closePlayer(){if(hls){hls.destroy();hls=null}$('#video').pause();$('#video').removeAttribute('src');$('#video').load();$('#playerModal').classList.remove('open')}
function search(){let q=$('#searchInput').value.trim().toLowerCase();let results=q?channels.filter(c=>(c.name+' '+c.category).toLowerCase().includes(q)):[];$('#searchResults').innerHTML=results.map(card).join('')||`<p style="color:#777">${q?'No channels found.':'Start typing to search.'}</p>`;$$('#searchResults .card').forEach(c=>c.onclick=()=>{closeSearch();openPlayer(c.dataset.id)});}
function closeSearch(){$('#searchOverlay').classList.remove('open');$('#searchInput').value='';$('#searchResults').innerHTML=''}
function bind(){window.addEventListener('scroll',()=>$('.nav').classList.toggle('scrolled',scrollY>40));$('#searchBtn').onclick=()=>{$('#searchOverlay').classList.add('open');setTimeout(()=>$('#searchInput').focus(),50)};$('#searchClose').onclick=closeSearch;$('#searchInput').oninput=search;$('#playerClose').onclick=closePlayer;$('#retryBtn').onclick=loadStream;$('#copyUrl').onclick=async()=>{try{await navigator.clipboard.writeText(current.url);$('#copyUrl').textContent='Copied';setTimeout(()=>$('#copyUrl').textContent='Copy stream URL',1200)}catch{}};$('#browseBtn').onclick=()=>$('.content').scrollIntoView();$('#heroPlay').onclick=()=>openPlayer(channels[0].id);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSearch();closePlayer()}});$$('[data-nav]').forEach(b=>b.onclick=()=>{let cat=b.dataset.nav; if(cat==='home')$('.content').scrollIntoView(); else {let target=cat==='live'?channels:channels.filter(c=>c.category.toLowerCase()===cat);renderRows(target);$('.content').scrollIntoView();}})}
function esc(x){return String(x??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
init();
